### ISSUE TITLE
Hint-Mode colors whole page

### ISSUE THREAD

**Issue by Skillmon** [cmcaine/tridactyl#111]
On [TeX.SX](https://tex.stackexchange.com/questions#) the hint mode colours the whole page yellow not only the hint-texts.

**Comment by bovine3dom** [comment]
Works fine for me: https://i.imgur.com/6FrsxfV.png

**Comment by Skillmon** [comment]
I'll try if another plugin is conflicting...

**Comment by Skillmon** [comment]
Might be closed as not reproducable. After I reload the page it works fine for me, too.

**Comment by bovine3dom** [comment]
Are you using the new-fangled hint mode for copying text, i.e, `;p`?

The whole page does go yellow then, but that's because you can select parent nodes to copy all the text contained in that node and its children.

It could be sensible to look at colouring elements that are partially contained within another element different colours.

Thanks for reporting the issue!

**Comment by Skillmon** [comment]
No, I just used `f`. I'm not sure whether the beta was active by that time or the 1.4.3 release version. Currently I run the beta and don't have the problem. The different colouring would be good, yes.

**Comment by Skillmon** [comment]
Sorry if I misuse this issue-thread, but where do I find all the default keybindings?

**Comment by bovine3dom** [comment]
`:help` has a link to them. It's not very intuitive yet. A way of getting messages back to users is on our todo list.

If you have many other casual questions, feel free to pop into chat - https://riot.im/app/#/room/#tridactyl:matrix.org
