### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by rgaiacs** [cmcaine/tridactyl#12]

**Comment by cmcaine** [comment]
I haven't put one on yet because I haven't decided what to go for.

Probably MPL or the more restrictive Affero GPL.

Do you have a preference?

**Comment by rgaiacs** [comment]
> Do you have a preference?

As long as you have a open source license I'm very happy. I don't remember the special clauses of the MPL so I would go with one of the GPL family.

**Comment by dumblob** [comment]
If I may also express my opinion on licenses, then I would ask myself the following questions:

1. Do I want to prevent businesses from using Tridactyl with their proprietary products without contributing any changes they made back to this upstream repository? If yes, then we have to choose a copyleft license. If no, then we shall choose a permissive license.

2. Am I afraid of SW patents (which are valid in certain areas like USA, but absolutely non-existent in others like Europe)? If yes, then some license explicitly covering the treatment in case any patents should be present. If not, then it doesn't matter and we shall choose one of the shorter licenses.

3. Can I imagine (or is it already foreseeable) incorporating into Tridactyl some other piece of software, which is under a copyleft license? If yes, than we shall not choose any copyleft license, because there is a high probability, that the two licenses won't be compatible (copyleft basically implies something along the line "The user must convey the entire program's source code under the terms of **this** license." in the license text).

4. Am I rather a fan of copyleft (restricting people and businesses for the sake of the SW itself) or a fan of permissiveness ("do whatever you like, but don't impose anything on me")?

MPL is copyleft and explicitly covers SW patents
GPL 3.x and its variants are copyleft and explicitly cover SW patents
BSD License(s) are permissive and do not cover SW patents
Apache 2.x license is permissive and does cover SW patents
MIT is permissive and does not cover patents (but is therefore minimal)
etc.

For further information please see the lists of licenses on https://www.gnu.org/licenses/license-list.html.en and https://fedoraproject.org/wiki/Licensing:Main and some FAQs on https://www.gnu.org/licenses/gpl-faq.html ).

I personally would advocate for MIT :wink:.

**Comment by cmcaine** [comment]
It's unclear to me what the GPL license means in an interpreted language like JS, and I don't want people to have to think about licenses, so I'm not going to pick it.

I don't think the non-liability clauses of software licenses are enforceable in my jurisdiction, but I'll suggest the MIT license anyway because it's a well-known permissive license and therefore less people need to think about licenses (if anyone ever wants to re-use this code).

@Koushien, @bovine3dom: Please comment here to the effect that you are happy for your past contributions to be licensed under the MIT license.

**Comment by bovine3dom** [comment]
Yeah, I'm happy with MIT.

**Comment by cmcaine** [comment]
My original pick of Apache v2 was probably better because it causes contributors to grant a license for their work:

>   5. Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.

Please instead state that you're fine with the Apache v2 :)

**Comment by bovine3dom** [comment]
Yeah, I'm happy with Apache v2.

**Comment by dumblob** [comment]
>My original pick of Apache v2 was probably better because it causes contributors to grant a license for their work

That's the reason why many projects require copyright waiver in the commit history.

**Comment by Koushien** [comment]
I'm OK with Apache v2.
