### ISSUE TITLE
Dark version of new tab page

### ISSUE THREAD

**Issue by qazip** [cmcaine/tridactyl#126]
The idea of tridactyl's new tab page is fantastic. Sadly, I use dark themes everywhere and whenever I open a new tab now, the white page blinds me.

It would be nice if you provided a new tab page with a dark background, either instead of the current page or as an option.

**Comment by bovine3dom** [comment]
Hi, you could avoid seeing the page with `bind t fillcmdline tabopen`.

Our intention is to allow all CSS to be user-configurable at some point, but it is moderately low down our list of priorities.

If you make some CSS that you would prefer, make a PR and I'll see what we can do.

**Comment by robsmith11** [comment]
Is there any way to force the Tridactyl newtab page to be dark with userChrome.css/userContent.css?

I'm using https://github.com/overdodactyl/ShadowFox , so everything is dark now except for the newtab page. :/

**Comment by robsmith11** [comment]
To answer my question, the colors for the newtab page can be controlled with `browser.display.background_color` and `browser.display.foreground_color`.

**Comment by overdodactyl** [comment]
I'm currently using my code found here:

https://github.com/overdodactyl/ShadowFox/blob/master/userContent-files/webextension-tweaks/tridactyl.css

to create a dark theme for both the new tab and the command line.

Here are some sample screenshots:

![screen shot 2018-02-28 at 11 23 50 am](https://user-images.githubusercontent.com/33071129/36805239-d045172c-1cb4-11e8-9f21-ce30dda3263a.png)

![screen shot 2018-02-28 at 11 27 39 am](https://user-images.githubusercontent.com/33071129/36805381-321481fe-1cb5-11e8-8315-0b4a355d3809.png)

The colors used are based on Firefox's [Photon colors](https://design.firefox.com/photon/visuals/color.html) as well as those used in the browser inspector/toolbox.

@robsmith11, since you already use ShadowFox, this might be an easy fix for you.  

@bovine3dom, is this a look you would be interested in trying to incorporate? If so, I'll see what I can do in terms of a PR

**Comment by bovine3dom** [comment]
@overdodactyl sure, but look at PR #255 as there is some overlap

**Comment by overdodactyl** [comment]
Oh nice, I hadn't seen that yet!

Sorry, should have given that a look first :)

**Comment by bovine3dom** [comment]
Added in #579.

**Comment by cmcaine** [comment]
@overdodactyl's css now lives here: https://github.com/overdodactyl/ShadowFox/blob/master/css/userContent-files/webextension-tweaks/tridactyl.css

We should use their colours and stuff in the default dark theme, I think.

**Comment by cmcaine** [comment]
Done.
