### ISSUE TITLE
Add vim-vixen evaluation

### ISSUE THREAD

**Issue by gsauthof** [cmcaine/tridactyl#154]
The README already evaluates three other vim-mode extensions. This is very helpful information because probably the no 1 question after searching for vimperator replacement in Firefox 57+ is: what are the difference between the available alternatives?

Currently, the evaluation doesn't include [vim-vixen](https://github.com/ueokande/vim-vixen).

In a very short comparison I noticed the following differences:

- the scroll distance with one `j` or `k` key press is larger with tridactyl than with vim-vixen
- vim-vixen has `:o` with some completions
- tridactyl needs more premissions

It would be great if you could add an evaluation of vim-vixen.

**Comment by cmcaine** [comment]
That content in the readme dates to when Olie and I were working out if we wanted to write this project at all and hasn't really been updated.

That said, I would like to keep a list of related projects. If you write an evaluation of vim-vixen I'll consider merging it.

I don't think the differences you've mentioned so far are really worth noting, though (Tridactyl also has `:open` with completion). I'd mention that binds are to function-style names (like Vimium and vimfx), that completion is better, that it's missing a bunch of features compared to Tridactyl. I'd also complain about the iframe security thing, if that's not sorted yet.

I'm probably missing some good parts of vim-vixen because I don't use it, so, if you do you could add some balance to that.

**Comment by bovine3dom** [comment]
It might be wise to add "date reviewed" to each of the alternatives, because they could fall out of date quite quickly.

**Comment by gsauthof** [comment]
I don't mind if your evaluation is a little bit biased. Almost anything would be better than nothing.

Do you have any details/link on the iframe security thing?

Yes, tridactyl has autocompletion with `:open` but it just silently fails on `:o` (no completion and no page is opened). With vimperator, `:o` worked as expected. vim-vixen does understand `:o`. I don't know who wants to use `:open` when you have `:o` - and when you are used to vimperator then tridactyl doing nothing on `:o` is quite irritating.

FWIW, the default scroll-distance used by tridactyl irritates me as well. The value vim-vixen uses is much better, especially if you are used to vimperator. Such details doesn't have to be included in a comparison. But perhaps you want to reconsider the default to improve usability.

Another difference I've noticed: vim-vixen has search integrated (`/` and `n`) while tridactyl has not.

**Comment by bovine3dom** [comment]
https://github.com/ueokande/vim-vixen/issues/251 is the Vixen issue.

`:o` is sensible, happy to add that alias.

**Comment by bovine3dom** [comment]
I'm going to close this as neither @cmcaine nor I feel it would be appropriate to review other add-ons on our own page. I think that should be the users' responsibility - a comparison of all of the various Vimperator alikes would make a nice blog post :)

I am open to moving the ancient "state of the art" from the readme into another folder or branch.
