### ISSUE TITLE
Ignore mode resets itself frequently while navigating feeds on newsblur.com

### ISSUE THREAD

**Issue by terminalmage** [cmcaine/tridactyl#176]
I've been using ignore mode to be able to cycle through stories on newsblur.com (RSS reader), and frequently ignore mode keeps exiting between stories. Looking at the web console, I see javascript logs from newsblur.com (all the `Array` ones below), followed by `Message` lines from Tridactyl once ignore mode exits.

```
Array [ "Hijacking view setting", 101749, " --> ", 101749, "feed" ] common.js:1388:155
Array [ "Hijacking view setting", 101749, " --> ", 101749, "feed" ] common.js:1388:155
Array [ "story show_next_story", {…}, -1 ] common.js:1388:429
Array [ "story show_next_story", {…}, -1 ] common.js:1388:429
Array [ "story show_next_story", {…}, -1 ] common.js:1388:429
Array [ "story show_next_story", {…}, -1 ] common.js:1388:429
Array [ "story title, switch story view", "feed" ]
Array [ "Hijacking view setting", 6783626, " --> ", 6783626, "text" ] common.js:1388:155
Array [ "Hijacking view setting", 6783626, " --> ", 6783626, "text" ] common.js:1388:155
Message:  Object { type: "excmd_content", command: "scrollline", args: […] } messaging.ts:26:8
Message:  Object { type: "excmd_content", command: "scrollline", args: […] } messaging.ts:26:8
Message:  Object { type: "excmd_content", command: "scrollline", args: […] } messaging.ts:26:8
Array [ "Real-time feed update", "256590", "story:new_count:1" ]
```

I've noticed that ignore mode exits when the page is refreshed, or if the tab is changed, so perhaps it's possible that some background JS stuff from newsblur.com is causing something to be reloaded that affects Tridactyl's state. This is just a nominally-educated guess, though.

I'm using `Version 1.6.1pre510` and I can't really find a version where this didn't happen, so I don't think it's a regression per se.

**Comment by Koushien** [comment]
What's happening is the loading in the subframes evoke the webNavigation.onBeforeNavigate listener([MDN reference]) in [controller.ts], reverting to normal mode each time.

That site is a bit much for this machine's Core 2 Duo; if you're building Tridactyl yourself can you try appending `&& details.frameId === 0` to the conditional in the line following the one I linked above (adding it to line 104)? That adds the condition that the navigation event must not be occuring in a nested iframe. I'm having luck with it so far, but your use may prove otherwise.

[MDN reference]:https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation
[controller.ts]:https://github.com/cmcaine/tridactyl/blob/7574146e653894fe9765ac7a3e46fa474c0fd2ac/src/controller.ts#L103

**Comment by cmcaine** [comment]
That onBeforeNavigate thing is a menace to hint mode too. Should really move the logic to the content script.

**Comment by Koushien** [comment]
@terminalmage, if you're keen and you're using ESR (I believe is supported), Developer Edition or Nightly, I built the extension current as of [`baaa4ce`] with my suggested change (actually only using `==` instead of `===`), into a `.zip` you can load in `about:debugging`. I figure you might get some mileage out of it before a refactor.

[`baaa4ce`]: https://github.com/cmcaine/tridactyl/commit/baaa4cef61820309d257096fcc4debe1cbf62dc1

**Comment by cmcaine** [comment]
Put Koushien's fix into master. Fixed in betas.

I had a quick look at making state per-tab, but it's a bit fiddly. Going to fix some other things first.
