### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Nefari0uss** [cmcaine/tridactyl#2]
Since there's not been some activity in some time, I'm just wondering if development of this application has stalled or died out.

**Comment by cmcaine** [comment]
It's on the to-do list, but I've been doing other things.

The most recent work on this project is in another repo on a webextention keyboard API.

If you are interested in the project, I still welcome collaborators: I do this partly for fun and I prefer working with a team rather than alone.

**Comment by Nefari0uss** [comment]
Sorry for the late reply but would you mind linking the other repo?

**Comment by bovine3dom** [comment]
https://github.com/cmcaine/keyboard-api                                                                                                                                                                                                                                                                                                                                                    From: notifications@github.comSent: 9 July 2017 15:51To: tridactyl@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [cmcaine/tridactyl] Is this dead? (#2)  Sorry for the late reply but would you mind linking the other repo?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cmcaine** [comment]
I haven't updated the github mirror in a while, but I'll push the latest work today for review.

Just cleaning it up for Mozillian reviewers...

**Comment by cmcaine** [comment]
Pushed a reasonable first version for reviewers with instructions on how to test it.

https://github.com/cmcaine/keyboard-api
