### ISSUE TITLE
Add support for multiple pipe-separated urls in open commands

### ISSUE THREAD

**Issue by behrmann** [cmcaine/tridactyl#219]
After a quick look I gather that quickmarks can only open a single website at the moment. In the past, with pentadactyl, I had multiple sites (e.g. all my webcomics) bound to a single quickmark. Being able to set a quickmark via `quickmark <key> <url>` would be a nice addition, even more so if url could be of the form `<url1 | url2 | ..>`.

**Comment by iago-lito** [comment]
Before this is added, would it be worked-around with a plain mapping like `:open <url><cr>:open <another_url><cr>..`?

**Comment by bovine3dom** [comment]
We don't support <CR> style binds yet.

There's a composite command: `composite cmd1 | cmd2 | cmd3` which might work.

**Comment by behrmann** [comment]
Actually, opening multiple urls seperated by pipes with `open` and `tabopen` would be a very nice addition in the first place. :)

**Comment by bovine3dom** [comment]
`bind blah composite tabopen url1 | tabopen url2 | tabopen url3` works (provided your URLs don't contain any pipes).

I'll add the `quickmark` command.

**Comment by behrmann** [comment]
Thanks for taking up the quickmarks suggestion!

> `bind blah composite tabopen url1 | tabopen url2 | tabopen url3`
>

Ah, sorry, I was aware of this option, but coming from pentadactyl I thought
that `open url1 | url2 | url2` was standard Firefox behaviour, which I just
checked, it is not generally so.

Firefox does support opening multiple urls seperated by pipes when setting the
homepage in the preferences and pentadactyl took this behaviour further and
supported it in its `*open` commands as well.

I do think, that supporting multiple pipe-seperated urls for the `open`-family
of commands is a better user experience than `composite tabopen url1 | tabopen url2`.

**Comment by bovine3dom** [comment]
`quickmark` now supports space delimited multiple urls - `quickmark t url1 url2 url3` - in baaa4ce.

They're space delimited because that's currently how most of the rest of our commands work, but it might be better to switch at some point to using pipes everywhere.

It will be some time before this appears on the AMO beta builds due to #205.


I agree that the composite command isn't very nice to use interactively - I was suggesting it as a workaround for the lack of multiple URL support on quickmarks (indeed, the quickmark command is currently just sugar for setting up multiple bind commands).

I'm happy to add pipe support to *open.

**Comment by behrmann** [comment]
On Fri, Dec 08, 2017 at 12:05:04PM +0000, Oliver Blanthorn wrote:
> `quickmark` now supports space delimited multiple urls - `quickmark t url1 url2 url3` - in baaa4ce.
>

Excellent, thank you!

> They're space delimited because that's currently how most of the rest of our
> commands work, but it might be better to switch at some point to using pipes
> everywhere.
>
> I agree that the composite command isn't very nice to use interactively - I
> was suggesting it as a workaround for the lack of multiple URL support on
> quickmarks (indeed, the quickmark command is currently just sugar for setting
> up multiple bind commands).
>

Yeah, I noticed that in the code, a perfectly good solution treating all
bindings equally.

> I'm happy to add pipe support to *open.
>

Wonderful. Looking forward to that.

**Comment by behrmann** [comment]
Since the initial complaint has been addressed in baaa4ce and the topic has changed, I'll changed the title.

**Comment by cmcaine** [comment]
The reason we have the `composite` command at all is because search queries and URLs can contain pipe characters (URLs aren't supposed to, by RFC 3986, but most webservers (or maybe it's the browsers?) seem quite happy to accept non ascii characters in URLs).

I'm not sure of a good way around this. Maybe pipes appear so infrequently in URLs and can be escaped manually from search queries that this isn't an issue.

**Comment by behrmann** [comment]
> The reason we have the `composite` command at all is because search queries
> and URLs can contain pipe characters (URLs aren't supposed to, by RFC 3986,
> but most webservers (or maybe it's the browsers?) seem quite happy to accept
> non ascii characters in URLs).
> 
> I'm not sure of a good way around this. Maybe pipes appear so infrequently in
> URLs and can be escaped manually from search queries that this isn't an issue.
> 

Well, Browsers go to great lengths to accept everything as a url that even
remotely looks like one, so I wouldn't bother too much in this case :) In the
past seven years I never had to escape a pipe in a url and only ever used them
for composition.

**Comment by bovine3dom** [comment]
Closing as #789 will be close to this:

`t URL1 ; t URL2 ; t URL3`
