### ISSUE TITLE
Make FAQ

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#232]
Questions to include:

- How can I change the search engine?
- How can I add a search engine?
- How can I import/export settings?
- How can I bind to modifiers?
- How can I tab complete from bookmarks?

Suggestions welcomed.

**Comment by glacambre** [comment]
Questions lifted from Gitter:
- When i type 'f', can i search for link names (like vimperator) in order to narrow down the space of link candidates?
- How to remap keybindings in both normal mode and ex mode?
- Where can I find a changelog for the different versions (to see what is new in the latest version)?
- Why can't I use my bookmark keywords?
- Why doesn't Tridactyl work on websites with frames?
- Can i change proxy via commads?
- Does Tridactyl use an external config file just like vimperator?
- How do I disable Tridactyl on certain sites?
Questions from issues where the word 'duplicate' has been written:
- How can I list the current bindings?
- Why doesn't Tridactyl work on some pages? (CSP)
- How can I know which mode I'm in/have a statusline?

**Comment by Koushien** [comment]
Probably obvious, but whenever the FAQ is completed, probably best to link to it in the readme/newtab/help and rewrite the latter two to reduce redundancy and make it more apparent they should consult the FAQ first. Correlates with #162.
