### ISSUE TITLE
Force normal mode

### ISSUE THREAD

**Issue by dannycolin** [cmcaine/tridactyl#266]
When I open an URL like Messenger.com, I'm automatically in insert mode. ~In fact, any~ Other webpages with a textarea also trigger that behavior. So, I would like to know if it's possible to always force the normal mode when I open an URL (like it should be in VIM) ?

**edit**
It looks like Messenger.com is stealing my focus evertime a switch to an other thread.

**Comment by johnbeard** [comment]
Not every page with a textarea does this - for example Wikipedia pages in edit mode don't do it for me.
I do see it on Riot.im (autofocus to the main chat input) and search engines (e.g. Google and DuckDuckGo).

For Google and DDG, this appears to be done with JS rather than with HTML `autofocus` (disabling JS stops autofocus).

For Riot, disabling JS kills the site. It doesn't even seem to use an input element for the chat input (magic of the modern web), so it's not even "focussed" in the traditional sense. 

I suppose a way to deal with this is to wait "some time" after page load, hope any focus stealing JS has run (and and `autofocus` elements have loaded) and then steal the focus back for Tridactyl normal mode?

**Comment by dannycolin** [comment]
> Not every page with a textarea does this - for example Wikipedia pages in edit mode don't do it for me.
I do see it on Riot.im (autofocus to the main chat input) and search engines (e.g. Google and DuckDuckGo).

I'll update my post ;).

> I suppose a way to deal with this is to wait "some time" after page load, hope any focus stealing JS has run (and and autofocus elements have loaded) and then steal the focus back for Tridactyl normal mode?

Sadly, that solution will not work with every websites. For example, Messenger.com (the facebook chat app) steal my focus everytime I switch to a different conversation thread.

**Comment by cmcaine** [comment]
The issue is that Tridactyl checks the target element for each keypress and changes between input and normal mode accordingly.

For most use cases that's a good thing.

We could distinguish JS vs manual focus changes by listening for focus events and checking their isTrusted() method. Don't know what kind of events autofocus emits.

@dannycolin What exactly is your preferred behaviour (esp. for messenger if the problem is happening within a single page application)? Do you have any suggestions for how it could be implemented.

**Comment by dannycolin** [comment]
> @cmcaine What exactly is your preferred behaviour (esp. for messenger if the problem is happening within a single page application)? Do you have any suggestions for how it could be implemented.

One way to implement it would be to have an option like `set forcemode [true|false]`. If the forcemode is *true* than the user need to explicitly change the mode by pressing a key. If *false*, it just default to the actual behavior of the plugin. With that option, we'll be able to emulate VIM's behavior.

I can see one limitation and it's that Tridactyl doesn't remember per tab the mode. But as I heard, you're working on that feature. So I don't know if we should wait for that feature to implement the one i'm proposing. What's your opinion?

**Comment by bovine3dom** [comment]
Simply `set allowautofocus false` in the latest betas. Cheers @glacambre!

**Comment by liviu-** [comment]
Note that this setting may interfere with the Jupyter notebook interface and other JS-based editors unless you whitelist them (`seturl <url> allowautofocus true`)

**Comment by bovine3dom** [comment]
Thanks for pointing that out. I've added it to the documentation.
