### ISSUE TITLE
Allow ex mode binds to be user-configurable

### ISSUE THREAD

**Issue by robertgzr** [cmcaine/tridactyl#278]
I would like to change the default binds of `tab` and `shift-tab` to cycle through the suggestions for the `:buffer`/`:open`/`:tabopen` commands to `ctrl-j/k`

**Comment by IsaacKhor** [comment]
How would this be implemented? A new `hints.upchar` and `hints.downchar` config option? Some kind of magic in `:bind`?

**Comment by johnbeard** [comment]
I think it would be valid to have this as the default (so there are two binds). LeaderF also uses Ctrl-J/K to cycle choices in its list.

(It doesn't use Tab, which is quite annoying when coming back from Tridactyl, but it does also use the arrow keys which mean history step in command mode (in vim and Tridactyl, so that's perhaps a bad habit!)

**Comment by bovine3dom** [comment]
It might be sensible to really treat this as "allow binds in all modes to be user-configurable" although we might have to do some thinking first...

**Comment by bovine3dom** [comment]
Closing in favour of #304.
