### ISSUE TITLE
Tridactyl breaks sometimes when updating

### ISSUE THREAD

**Issue by R030t1** [cmcaine/tridactyl#290]
None of the hotkeys work. I tried reinstalling.

**Comment by johnbeard** [comment]
I usually (always, maybe?)I see the same thing when updating via the add-on page.

**Comment by Koushien** [comment]
How did you guys relieve this, if you have at all? Refresh page, restart browser, `Shift+Esc`?

**Comment by johnbeard** [comment]
I normally restart the browser.

**Comment by cmcaine** [comment]
It would be good to try and understand why this happens. Maybe there's a 'start extension' event we're supposed to listen to?

Seems unlikely, but if not I don't understand why reloading the content pages doesn't fix it.

**Comment by glacambre** [comment]
Does this bug still happen? I can't seem to reproduce it by disabling and re-enabling the extension with Firefox 58.0.1 on Linux and Tridactyl 1.7.3.

**Comment by bodograumann** [comment]
Not sure if this is the exact issue, but tridactyl just completely stopped working. There was an update from 1.10.0 to 1.10.1, which might have caused this. The new tab page was not set to the tridactyl-one, but disabling+enabling tridactyl initially didn't fix that.
Only after restarting firefox and then disabling+enabling tridactyl did it work again.

I'm running a binary firefox 59.0.2 on gentoo linux.

**Comment by dotancohen** [comment]
I am having an experience similar to bodograumann. I don't know if it is the same bug, but I cannot get Tridactyl (1.10.1) to run either. I disabling/renabling Tridactyl, then restarting Firefox (59.0.2), then disabling/reenabling Tridactyl again. No good.

The problem _may_ be due to the fact that I initially declined giving Tridactyl new permissions on a recent upgrade, related to the new messenger service. What other information should I provide to help find the bug?

**Comment by bovine3dom** [comment]
If you open a simple page like www.txti.es and open the web console (Firefox hamburger menu, developer tools, web console), do you see any errors? Same goes for browser console.

Also, see if Tridactyl is listed under about:debugging, tick enable debugging (owtte), click debug on Tridactyl and type console.log(tri) into that console and see if it exists.

**Comment by bovine3dom** [comment]
Potential workaround:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onUpdateAvailable

Just adding a listener to that event will prevent Tridactyl from being updated while Firefox is running; instead, updates will happen only on a browser restart.

Later, we could potentially do some clean up in the callback for that event, and then call `runtime.reload()` to tell Tridactyl to update itself.

**Comment by martinstannard** [comment]
@bovine3dom tridactyl has broken for me too, on Firefox 59.0.2, Tridactyl 1.11.0. I've uninstalled, reinstalled, restarted browser, enabled/disabled.

Home page is now standard firefox, and if I try the debugging steps above I get: ReferenceError: tri is not defined[Learn More] debugger eval code:1:1

**Comment by bovine3dom** [comment]
@martinstannard Thanks for taking the time to help debug. Could you copy your Firefox profile folder (found via about:support) somewhere (locally! It's full of juicy details...), downgrade to version 1.10.1 via https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/, see if Tridactyl works, go to about:addons click Check for updates on the little cog, and see if Tridactyl works.

I've basically no idea what's wrong so I'm hoping that the problem is something between the versions rather than the add-on updater destroying profiles every now and then...

**Comment by bovine3dom** [comment]
Additionally, if you could try the above again on a fresh Firefox profile (on Linux do `firefox -P`) to which you have copied your extension storage from the old profile: `<Profile folder>/firefox/<your profile>/storage-sync.sqlite` and `<profile folder>\Firefox\Profiles\<profile>\browser-extension-data\tridactyl.vim@cmcaine.co.uk\storage.js` if it exists.

Thanks again for your time. I'm very sorry that it's broken, and you're probably not the only ones as we've seen a slight downturn in the number of people using the add-on.

**Comment by bovine3dom** [comment]
@cmcaine and I have been talking about this and we really have very little idea what is wrong, other than that it is probably caused by Firefox updating Tridactyl while it is running.

It would be nice to figure out what is wrong, but if we can't, I suspect the solution is to delete all your extension storage as mentioned above, see if that fixes it, and if it doesn't, just start with a fresh profile and copy across the bits you want (e.g. browser history). A different workaround would be to use one of our [beta builds](tridactyl.cmcaine.co.uk/betas) as these get a separate extension storage and ID.

I'm reasonably sure that 0da814c will prevent this from happening again, so we'll release that in version 1.11.1 today and hopefully no-one will have to use a work-around again after that...

**Comment by bovine3dom** [comment]
I think this is probably fixed now. I haven't heard of any complaints since.
