### ISSUE TITLE
D (shift+d) to close the current tab then go to the previous tab, rather than the next

### ISSUE THREAD

**Issue by glittershark** [cmcaine/tridactyl#337]
Vimperator/Pentadactyl had this, and my muscle memory still hits it all the time - it'd be nice for tridactyl to have it too.

Since this seems pretty trivial to implement, I'd love for this to be my first PR, if someone can point me in the right direction for implementing it!

**Comment by bovine3dom** [comment]
Does `composite tabclose | tabprev` do what you want?

In which case, adding a bind to config.ts for D should suffice.

**Comment by behrmann** [comment]
@glittershark thanks for opening this, I've meant to open this issue for ages already. 

I had bound `composite tabclose | tabprev` for a while, but it has a very noticable "jump" in between, i.e. it closes the tab, you see tab `n+1` popping up, than you switch back to tab `n` (formerly `n-1`). For a short while I tried `composite tabprev | tabclose #` as a workarount, but this had some corner cases I don't remember anymore and now there is also #341.

A solution that would implement close+tabprev as an atomic operation, at least without the noticable flicker of the next tab, would be wonderful.

**Comment by bovine3dom** [comment]
@behrmann Yes, Lexi mentioned this as an issue on Riot the other day.

In which case, @glittershark, I'd look at the function tabclose in excmds.ts. There's some magic going on with macros that you don't need to worry about; you just need to know that anything typed into the Tridactyl command line after `tabclose` gets turned into arguments split up by spaces.

I'd recommend an approach like the one we took with the `winopen` function, where you check to see if the first argument is a string flag that you have a special case for, (e.g. "-p"), then execute the function tabprev(), pop the first argument from the array, and continue the function as normal.

**Comment by bovine3dom** [comment]
Added and bound to `D` in the latest betas.

**Comment by bovine3dom** [comment]
@behrmann you can try `composite tabprev | sleep 1 | tabclose #` - it works fine on my machine but I wanted to make some allowance for slower ones.

**Comment by behrmann** [comment]
Thanks! Works like a charm on my machine as well.

**Comment by behrmann** [comment]
I noticed today, that the performance, at least on my machine, changed in such a way that a `sleep 1` is not sufficient anymore for the list to update. 

Wouldn't it be possible to internally keep a stack of which tabs were accessed in which order, so that we don't have to wait for the buffer list to update or just make the update faster?

**Comment by bovine3dom** [comment]
> Wouldn't it be possible to internally keep a stack of which tabs were accessed in which order, so that we don't have to wait for the buffer list to update or just make the update faster?

See #242, but the easiest thing would be to write a special function for `D` in excmds.ts.  In pseudocode:
```
tab2die = currenttab()
tabprev()
tabclose(tab2die)
```

I'm currently working on userChrome but would be happy to accept a PR or give you pointers.

**Comment by behrmann** [comment]
I know, special casing is ugly, but wouldn't 
```typescript
export async function tabclose(...indexes: string[]) {
    if (indexes.length == 1 && indexes[0] == "#") {
        let id: number
        id = await activeTabId()
        tabIndexSetActive((await activeTab()).index)
        browser.tabs.remove(id)
    } else if (indexes.length >= 1) {
        let ids: number[]
        ids = await Promise.all(indexes.map(index => idFromIndex(index)))
        browser.tabs.remove(ids)
    } else {
        // Close current tab
        browser.tabs.remove(await activeTabId())
    }
}
```
be the quickest solution? I'm sorry if the syntax is humbug, I've never written a line of JS in anger and have no idea of the APIs and just started randomly guessing from the rest in `excmds.ts`.

**Comment by bovine3dom** [comment]
I'm a bit confused as to what you're trying to do there. `tabclose #` currently closes the previously used tab.

My reading of your code would make `tabclose #`:

1. Make a note of the current tab's internal ID
2. Make another note of the current tab's internal ID, and then use our function for setting tabs based on their Tridactyl user-facing ID, which as far as I can see is a very convoluted way of switching to the tab on the left.
3. Close the tab we just switched away from.

So I guess it does do what you wanted it to... but that's pretty impressively obfuscated; and also it stops tabclose from doing what it says on the tin: tabclose closes the tab with the user facing index supplied. # is the index for the previously used tab. It would make more sense if you had a special string, e.g. `tabclose %_but_then_go_left`.

I'm a bit tired so I might be completely misreading your code.

My suggestion would be:
```js
export async function tabclose_L(){
    const tabid = activeTabId()
    tabprev()
    tabclose(idFromIndex(tabid))
}
```

...or something along those lines. Again, sleepy, so that code is probably nonsense.

**Comment by behrmann** [comment]
Yeah, sorry, same problem here. My brainfart was to assume I could shoehorn the functionality to `tabclose`, which doesn't rally make sense. I'll revisit it tomorrow and have a look which ID is what first, as well.

**Comment by bovine3dom** [comment]
Tangentially related to this issue - FF65 has a new API we can use to change this behaviour "permanently", e.g, https://qiita.com/piroor/items/ea7e727735631c45a366
