### ISSUE TITLE
Search queries with colons fail

### ISSUE THREAD

**Issue by stevenbell** [cmcaine/tridactyl#352]
If I type a query containing a single colon (such as "error: no input files"), I get an "The address wasn’t understood" error from Firefox, indicating that it tried to interpret the query as an address.

If I type a search query containing "::" (such as "std::map usage") into the command line, I get taken to a an empty page:  moz-extension://6fe7bbd3-49e0-4613-8765-ab2c114349cf/std::map%20usage

In both cases, typing the query into the URL bar takes me to the appropriate search page.

**Comment by cmcaine** [comment]
If you use `s` and `S` instead of `o` and `t` you'll explicitly search for the string instead of relying on our URL auto-detection.

It is probably a bug that our code thinks "std::map" is a URL, though. Relevant code: https://github.com/cmcaine/tridactyl/blob/b7a833fcf5d2a4bccd306f1d561152444cac27d6/src/excmds.ts#L122

Problem is that `new URL('std::map')` works fine. You could contribute to solving this by finding firefox's algorithm on http://searchfox.com or by coming up with a replacement forceURI function that classifies appropriately.

If you don't think you're up to that then no worries. Someone will get around to it.

**Comment by cmcaine** [comment]
Fixed in betas > 1.9.3pre844

Get the betas at https://tridactyl.cmcaine.co.uk/betas/
