### ISSUE TITLE
Github hijacks the search command

### ISSUE THREAD

**Issue by utsekaj42** [cmcaine/tridactyl#374]
On Github when I try to search within a page by typing `/` to search the input is instead captured by the Github search bar.

**Comment by glacambre** [comment]
This is a known issue. There's not much we can do since `/` is a firefox keyboard shortcut, not a tridactyl one.
Once the find command ( https://github.com/cmcaine/tridactyl/issues/64 ) is completed we might be able to prevent github from hijacking the `/` shortcut.

One a side not, github hijacks other keybindings (and we might be able to do something about these). The keybindings are hijacked when selecting the "search" input field on https://github.com/cmcaine/tridactyl/issues , adding a word, pressing "enter" and then using "gi". The input field won't be selected and every keypress will be read by github instead of Tridactyl.
I suspect this is caused by Tridactyl not realizing it should go back to normal mode once "enter" has been pressed but I'm not a 100% sure.

**Comment by cmcaine** [comment]
> I suspect this is caused by Tridactyl not realizing it should go back to normal mode once "enter" has been pressed but I'm not a 100% sure.

Mode is supposed to change on the basis of the target of the target of each keyevent:

```ts
// src/controller.ts
                // This code was sort of the cause of the most serious bug in Tridactyl
                // to date (March 2018).
                // https://github.com/cmcaine/tridactyl/issues/311
                if (state.mode != "ignore" && state.mode != "hint" && state.mode != "input" && state.mode != "find") {
                    if (isTextEditable(keyevent.target)) {
                        if (state.mode !== 'insert') {
                            state.mode = "insert"
                        }
                    } else if (state.mode === 'insert') {
                        state.mode = "normal"
                    }
                }
```

The problem is that that code doesn't know that `input` mode should also be exited automatically.

This patch probably fixes it, but can't test right now.

```diff
diff --git a/src/controller.ts b/src/controller.ts
index 1073c54..6945b39 100644
--- a/src/controller.ts
+++ b/src/controller.ts
@@ -42,10 +42,10 @@ function *ParserController () {
                 // https://github.com/cmcaine/tridactyl/issues/311
                 if (state.mode != "ignore" && state.mode != "hint" && state.mode != "input" && state.mode != "find") {
                     if (isTextEditable(keyevent.target)) {
-                        if (state.mode !== 'insert') {
+                        if (!['insert', 'input'].includes(state.mode)) {
                             state.mode = "insert"
                         }
-                    } else if (state.mode === 'insert') {
+                    } else if (['insert', 'input'].includes(state.mode)) {
                         state.mode = "normal"
                     }
                 }
```

**Comment by bovine3dom** [comment]
If for some mad reason you want `/` to use GitHub's built-in search, just `set leavegithubalone true`.
