### ISSUE TITLE
Unable to create new binds

### ISSUE THREAD

**Issue by dannycolin** [cmcaine/tridactyl#401]
**Expected behavior**

```
reset d
bind dd tabclose
```
`dd` should close the current tab.

**What happens**

`d` is correctly resetted to an empty value but when I use `dd` Tridactyl stop working completly. If I restart Firefox I can use Tridactyl as long as I don't use a bind I've created.

**How to revert it**

Right after you restart Firefox, use `reset` on your custom bind and rebind the default one. 
```
reset dd
bind d tabclose
``` 

**Notes**

- Reloading the current tab doesn't reactivate Tridactyl
- Opening a new tab reactivate Tridactyl but I still can't use my custom bind because it re-kill it. Plus, there's a weird lag when I scroll.
- I've also tested with other bind combinaisons like `dq` and with other commands like `tabopen`. I've got the same result.
- #400 seems to have the same problem but I feel opening a issue with more information would be a good idea instead of commeting that issue. Feel free to refer one to the other.

**Comment by glacambre** [comment]
Replacing https://github.com/cmcaine/tridactyl/blob/1ef49cb6e841f721b332bcdaf0c34f79599d0a64/src/parsers/normalmode.ts#L11with `!result.value` fixes Tridactyl completely breaking but doesn't make `dd` work.

**Comment by cmcaine** [comment]
You're using `reset` as if it was `unbind`.

`reset` returns the bind to it's default value. `unbind` removes the bind.

So `reset d | bind dd tabclose` ends up with both binds active.

The problem is that if you have one bind as a prefix of another, the keyseq parser sees that there are two possible mappings and waits for more input.

I wrote the keyseq parser a while ago with the assumption that mappings that are prefixes of other mappings wouldn't be permitted, but we've never set up that validation.

Anyway, I'll fix that now.

**Comment by cmcaine** [comment]
The confusion is that for non-default binds, `reset` and `unbind` have the same effect.

**Comment by glacambre** [comment]
@cmcaine Even when using `unbind` instead of `reset`, Tridactyl breaks. #402 fixes it though.

**Comment by cmcaine** [comment]
Yep, they're two different problems. I'm going to fix the unbind one too, but in a slightly different way to you: I want to keep this "empty string means unbound" assumption out of the keyseq code.

**Comment by dannycolin** [comment]
> You're using reset as if it was unbind.

I've also tried with `unbind` and had the same result. The problem with `unbind` is that the bind still exists in the config and with reset it delete it (even for `d`). So, that's why I also tried with `reset`.
