### ISSUE TITLE
allowautofocus false / DOM focus hijack broken

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#405]
```
~/p/tridactyl ((3dee8a45…)|BISECTING|✔) $ git bisect good                      
ec51fbba8843fd7077b642dc9058e67da8f307fd is the first bad commit               
commit ec51fbba8843fd7077b642dc9058e67da8f307fd                                
Author: Colin Caine <cmc@cs.man.ac.uk>                                         
Date:   Thu Apr 19 15:21:56 2018 +0100                                         
                                                                               
    Fix newtab redirection                                                     
                                                                               
    Broken by hijack code. I've just assumed any page we load content.ts on    
    manually doesn't need hijacking. Other solutions are available.            
                                                                               
:040000 040000 d1124e6dc494d215c9aeb585d6eb33e2adc18a88 f3479f59c4cfaefc7e29810
a85c829b1edbf6693 M     src                                                    
```

Suggest addition of `if (author == "Colin" and attempt <= 3) attempt++; error("Code requires further testing"); end` to pre-commit hooks, or some kind of Pigouvian tax.

(I just lost half an hour of my life debugging my new `g;` only to find it wasn't my fault :( )

**Comment by glacambre** [comment]
I'm responsible for the focus hijacking code, I should be the one whose name should be checked against :p 

Sorry about that. I assume the bug you've been experiencing is not being able to focus elements in the page using `elem.focus()`? If yes, I'm very surprised this is happening since we're only breaking the page's `focus()` function, not the extension's.

**Comment by bovine3dom** [comment]
Nope, it's @cmcaine's fault. In https://github.com/cmcaine/tridactyl/commit/ec51fbba8843fd7077b642dc9058e67da8f307fd he stopped calling the DOM hijack code on loads of pages.

**Comment by cmcaine** [comment]
Oh FFS. They expose an exportFunction function in the global namespace
somehow but don't attach it to the global object.

Why do they do these things.

**Comment by cmcaine** [comment]
Fixed in 8ee9db1

**Comment by glacambre** [comment]
Does fixing this also fix `gi` not focusing the last input?

**Comment by cmcaine** [comment]
Yes

On 20 Apr 2018 3:36 p.m., "glacambre" <notifications@github.com> wrote:

Does fixing this also fix gi not focusing the last input?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cmcaine/tridactyl/issues/405#issuecomment-383116692>,
or mute the thread
