### ISSUE TITLE
Ability to "shell out"

### ISSUE THREAD

**Issue by timokau** [cmcaine/tridactyl#413]
I'm assuming this is a webextensions limitation, but it can't hurt to ask anyways. Would it be possible to "shell out" like this: `:!echo "Hello world"`? That would work great in combination with the new `hint -W`, enabling something like `hint -W !mpv`.

**Comment by bovine3dom** [comment]
Yeah, it's coming with the native messenger (for Linux, at least). We were going to merge it today but decided to wait until more people had updated to 1.9.4 as that contains the warning that you will need to manually confirm that you want to update with the new permissions. (Approx 20% of people are trapped on version 1.7 because of the last extra permission at needed...)

**Comment by bovine3dom** [comment]
`! [command]` works in the latest betas on Linux if you have the native messenger installed (OSX is broken, see #429).

The space between the exclamation mark and the command is required!
