### ISSUE TITLE
Can't use arbitrary comand as editorcmd

### ISSUE THREAD

**Issue by glacambre** [cmcaine/tridactyl#431]
First, a big thank you to @bovine3dom, @cmcaine, @IsaacKhor and @johnbeard for the native messenger, it's one of the most important features Tridactyl needed in order to reach feature-parity with Pentadactyl!

Now I'm encountering a little issue with spawning an editor when pressing `<C-e>` in a text input. I changed my editorcmd to `set editorcmd urxvt -e nvim -c "call feedkeys('GA')"` to have Neovim place the cursor in insert mode at the end of the document but it didn't work. I believe this is due to the split that happens here:
https://github.com/cmcaine/tridactyl/blob/2df99412eff69babdb30c3f2cb2a21b82dbc5397/native/native_main.py#L74

I think this could be fixed by just throwing the whole line to `sh -c`. I believe this would also have the advantage of not having to re-implement pipes ourselves. Are there disadvantages that I haven't thought about?

**Comment by bovine3dom** [comment]
That might work. Have you tried it? You can edit the native messenger yourself on disk. It's probably in .local/share/tridactyl (just don't do anything complicated as Tridactyl will overwrite it whenever it feels like it unless you change nativeupdatecmd, IIRC).

I already tried shell=True, but on my machine that just didn't work. I assumed it was because I was using Fish, as all sane people do, but reading the documentation again it seems to say that it will execute in sh, so maybe I just messed up.

The one benefit to not hard coding sh is that it's more likely to work on Windows.

**Comment by cmcaine** [comment]
We'll need to special case windows anyway.

> I think this could be fixed by just throwing the whole line to sh -c. I
believe this would also have the advantage of not having to re-implement
pipes ourselves. Are there disadvantages that I haven't thought about?

Just using sh directly was pretty much what I suggested last night but it
was too late to bother fixing it. I think it is a better approach.

**Comment by bovine3dom** [comment]
Fixed in 2231f5c.

**Comment by cmcaine** [comment]
You have to manually update the native messenger by running the install script again, btw.

**Comment by cmcaine** [comment]
I did, anyway.

**Comment by bovine3dom** [comment]
You really shouldn't have to manually update, it should update with Tridactyl :/

**Comment by glacambre** [comment]
The native messenger updated itself automatically on my machine. Thanks for fixing this!
