### ISSUE TITLE
Can <Ctrl-E> in insert mode be configured by any chance?

### ISSUE THREAD

**Issue by janzhen** [cmcaine/tridactyl#444]
In MacOS, `<Ctrl-E>` in editable area is usually used for "move to the end", just like Emacs. So, could this binding be configured by any chance?

**Comment by cmcaine** [comment]
Can you recommend an alternative binding for mac users?

**Comment by bovine3dom** [comment]
In general, you can't rebind it yet: see #304, but we can change it if you have a better idea.

While we've got you here, do you have any idea how to open vim in the terminal programmatically on OSX? I couldn't find any way of telling the terminal to open and execute a command, which is why we're using `open -nWt`, which opens your default text editor, but as far as I can tell you can't change that without fighting with the terminal.

**Comment by janzhen** [comment]
@bovine3dom Is this work?
```
open -a /Applications/MacVim.app -nW test.txt
```

**Comment by janzhen** [comment]
@cmcaine How about vimperator's <C-i>?
https://github.com/vimperator/vimperator-labs/blob/master/common/content/editor.js#L707

**Comment by bovine3dom** [comment]
@janzhen, oh, woops, thanks. I could have sworn it was ^e but obviously I was just wrong.

I'll give your command a go, but you can try it yourself with `set editorcmd open -a /Applications/MacVim.app -nW`.

**Comment by janzhen** [comment]
Have tried

```set editorcmd open -a /Applications/MacVim.app -nW```

and equalavennt

```set editorcmd open -nWa MacVim``` .

Both work.

But there is another problem. `open -W` will wait until app exits, so closing window will not return, have to cmd+q quit the app entirely.

**Comment by bovine3dom** [comment]
Fixed in latest betas (on both counts).

**Comment by janzhen** [comment]
Thank you very much.
