### ISSUE TITLE
Link to beta builds is broken

### ISSUE THREAD

**Issue by ExcaliburZero** [cmcaine/tridactyl#52]
The link to the beta builds for tridactyl in the Installing section of the readme file does not seem to work, as it links to a page not found.

https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/beta

![tridactyl_01](https://user-images.githubusercontent.com/4276196/32702358-06aacbd2-c7b4-11e7-823d-329c79bb275b.png)

**Comment by bovine3dom** [comment]
Thanks. We've just been unlisted for messing up a couple of things related to the AMO. Hopefull the page will be back up soon.

**Comment by cmcaine** [comment]
We got delisted because webpack sources are considered obfuscated and mozilla wants sources zipped and sent to them (apparently a link to github not enough).

We're working on it.

In the meantime this is the latest release

[tridactyl-1.0.7pre287-an+fx.zip](https://github.com/cmcaine/tridactyl/files/1465016/tridactyl-1.0.7pre287-an.fx.zip)

**Comment by Bzly** [comment]
You're listed again now; issue can be closed - unless eventual solution is to have a mirror somewhere other than Moz addons?

**Comment by terabyte** [comment]
In repos I manage, I use github's ability to upload a release associated with a tag to host artifacts.

**Comment by caputchinefrobles** [comment]
I'm not shure but I think beta builds are missing again. Is that confirmed? 
https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/beta

![screenshot_20180402_105518](https://user-images.githubusercontent.com/8964036/38198776-816b267c-3664-11e8-85b3-c9342d76c7cf.png)

**Comment by bovine3dom** [comment]
See #307. Where did you find the link to the betas?
