### ISSUE TITLE
Setting "newtab" to a file:// url opens two new tabs

### ISSUE THREAD

**Issue by wavexx** [cmcaine/tridactyl#530]
I'd like to set the new tab page to a file:// url in order to customize what I see (in fact, I just want a plain *empty* page).

Setting newtab to a file:// url doesn't work without the native extension, as "expected".

But with the extension, what happens is that Ctrl+t open a new empty tab, followed by an additional tab containing the actual file:// url. This only happens with file:// urls as far as I can see.

FF 59-60.

**Comment by bovine3dom** [comment]
It also happens with most about:* URLs. It's because we fall back to `nativeopen` for URLs that we can't open normally, and `nativeopen` must open URLs in new tabs - see #433.

Our configuration documentation will improve with #524 and hopefully that will at least warn some people of this behaviour. Closing in favour of those two issues.

**Comment by wavexx** [comment]
Sigh, this is so frustrating :/
Since quantum, half the time the bindings do not work as one would expect.

On top of this, the GTK input methods now overrides FF keybindings. This makes almost *all* keybindings inactive inside any text field, for example in the URL bar. Ctrl+w for example now works only if you focus outside of the field.

Not complaining to trydactyl here, I love it. Just venting some *massive* frustration here...
As a developer I'm pretty much forced onto the latest FF.

**Comment by aureooms** [comment]
As a quick fix, you could use a local server and set your homepage and new tabs to `localhost/something`.
