### ISSUE TITLE
Font size in <code> tags on Tridactyl new tab page too small

### ISSUE THREAD

**Issue by Bzly** [cmcaine/tridactyl#55]
The example commands written in `<code>` tags on the Tridactyl new tab page are in slightly too small a font and are too difficult to read (perhaps just on HiDPI displays).

![Left: readable. Right: Not](https://i.imgur.com/JtH1HZU.png)

**Comment by cmcaine** [comment]
Are you sure this is DPI related? I don't think DPI should affect relative font size like that.

I think this issue is probably font dependent. Perhaps we should just package some fonts?

Have any favourites? I'd just go with Noto Mono.

**Comment by Bzly** [comment]
No - more possibly to do with how I have my setup. I only have a small amount of display scaling up on my HiDPI laptop screen, so normal sized text for everyone else appears quite small for me. Of course, this does mean that slightly smaller still text is nigh on unreadable - even when it wouldn't be for most others. 

I'm unsure whether this is the case in this instance, though. Does it look a bit too small to you (whey!)?

**Comment by Bzly** [comment]
(To be clear, I'm mentioning this as a slight possibility; I do believe it's not a setup-specific issue, possibly the font, possibly just the CASE. I don't know how the stuff in code tags is styled.)

**Comment by Bzly** [comment]
*CSS, fecking Android autocorrect.

**Comment by bovine3dom** [comment]
I get the same issue on my nettop, with PixelsPerPx set to 2.

**Comment by cmcaine** [comment]
Can you have a look and see if you're using the same fonts in the good case and bad case? If not, we just need to bundle a font. If you are using the same font we need to think about this more.

**Comment by Bzly** [comment]
Fonts are indeed different in the two cases. The better is [Liberation Mono](https://pagure.io/liberation-fonts). Looks like we are allowed to bundle it - if you're happy with the choice, Colin. 

The Windows box here has decided to use Courier New as the font of choice, and we definitely need to spare our Windows users that particular eyesore.

**Comment by bovine3dom** [comment]
I think the problem is actually in about:preferences.For me, default font size is 16pt, but Monospace was set to 12. Changing that to 16 made it sensible for me.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 15 November 2017 12:43 pmTo: tridactyl@noreply.github.comReply to: reply@reply.github.comCc: oliver.blanthorn@postgrad.manchester.ac.uk; comment@noreply.github.comSubject: Re: [cmcaine/tridactyl] Font size in  tags on Tridactyl new tab page too small (#55)  Fonts are indeed different in the two cases. The better is Liberation Mono. Looks like we are allowed to bundle it - if you're happy with the choice, Colin.
The Windows box here has decided to use Courier New as the font of choice, and we definitely need to spare our Windows users that particular eyesore.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Bzly** [comment]
Is this latest commit to master on the beta branch of AMO?

Also, I realise it's a separate issue but we may want to consider bundling a font to get around the (again) silly default that the Firefox Windows client chooses.

**Comment by Bzly** [comment]
Yes, it is, and solves this particular issue.
