### ISSUE TITLE
don't say "Error" twice

### ISSUE THREAD

**Issue by jcrowgey** [cmcaine/tridactyl#617]
When I get the message about an unexpected error, it actually says:

```
# Error: Error: An unexpected error occurred 
```

They way I generated this situation is documented in #616---a corrupted/incorrect places.sql file in the profile and then tried to set a bookmark.  However, I imagine since this error is actually bubbling up from the browser that there should be other repro cases.

I'd mark this as low priority, but if someone knows which part of the code is catching these messages and putting them into fillcmdline, then I can take a stab at fixing.  I suppose it's in the logging.ts file.  But it's not completely clear to me the right fix.  I could, of course, check that 'message' starts with "Error:" and then not prepend "Error", but there's probably a more principaled way to tell which is not completely obvious to me based on my short exposure to this codebase.

**Comment by glacambre** [comment]
I think you have the right idea. I could be wrong but I don't think we do much with error messages besides concatenating strings.

**Comment by bovine3dom** [comment]
Sorry for stealing your thunder, @jcrowgey, but it was such a simple fix that by the time I saw what needed fixing it would have been silly not to just change it myself.

`src/logging.ts` is a bit weird because it's used everywhere, and webpack's approach to circular dependencies is to give up without saying anything (an outlook I can sympathise with), so we do everything from scratch there.

**Comment by jcrowgey** [comment]
@bovine3dom No need to apologize.  I had no thunder to steal.  I admit that I looked at those lines and thought about offering up almost exactly the changes you wrote in b1211bd, but I hesitated in case there were other places where the code was relying on `logging.ts` to say "Error".  In any case, thanks for taking care of it!
