### ISSUE TITLE
Support jump-to-tab in any window like vimium 'T'

### ISSUE THREAD

**Issue by dansanduleac** [cmcaine/tridactyl#62]

**Comment by bovine3dom** [comment]
Last time I tried this, just setting a tab to active in other windows selected that tab, but did not bring the window to the foreground. There is probably another API for doing that.

So yes, we intend to support this eventually.

**Comment by glacambre** [comment]
I thought this would be just a matter of adding `browser.windows.update((await browser.tabs.get(id)).windowId, { focused: true })` to [tabSetActive](https://github.com/cmcaine/tridactyl/blob/cd3580ee86311ff625c0babc550800780c9848c4/src/excmds.ts#L503) and replacing `currentWindowTabs` with `allWindowTabs` in [updateOptions](https://github.com/cmcaine/tridactyl/blob/cd3580ee86311ff625c0babc550800780c9848c4/src/completions.ts#L594) but it is actually slightly more complicated than that.

`:buffer` takes the index of the tab in the window. This means that it can't switch to tabs in other windows. To work around that, we could make it take tab ids instead but `:buffer` would become unusable without completions and we wouldn't be able to use `:b 3` to just go to the third tab.
Other options include adding a flag to `:buffer` to make it interpret its argument as a tab id instead of a tab index or creating a new function (e.g. `bufferall`) which would take tab ids as argument. I'm not sure what the best approach is.

**Comment by bovine3dom** [comment]
I think bufferall is probably the best idea.

I had this as blocked by completions because I thought the rewrite was coming soon but I doubt that will happen, so I'd happily merge something that added bufferall and completions for it.

**Comment by bovine3dom** [comment]
Bound to `B` by default from 1.13.0-70-gbe5c4e2.
