### ISSUE TITLE
Override page keybindings?

### ISSUE THREAD

**Issue by shalomb** [cmcaine/tridactyl#621]
The new github "search or jump to" feature maps `/` to set focus on the search box - which is more-often-than-note what you don't want as a tridactyl user. And there are countless other sites that do this (e.g. gmail, bitbucket, etc). This raises the question as to whether tridactyl should _allow_ pages to _hijack_ the maps/keybindings set either by default by tridactyl or those maps set by the user. Pentadactyl does this very well and ensures consistency - and IMO, tridactyl ought to as well.

It may be the case this is not possible - if so, Is there a way in tridactyl to override the maps/keybindings a page imposes?

**Comment by glacambre** [comment]
The page doesn't hijack Tridactyl's search command, it's just that Tridactyl doesn't bind anything to <kbd>/</kbd> because <kbd>/</kbd> is a default Firefox keyboard shortcut.
The current workaround suggested in https://github.com/cmcaine/tridactyl/issues/374 is to bind <kbd>/</kbd> to the `find` command. This isn't done by default because the command can be a bit slow on big pages.

**Comment by bovine3dom** [comment]
Closing in favour of #64.
