### ISSUE TITLE
Can't run installnative command on OSX without Python 3

### ISSUE THREAD

**Issue by pequodification** [cmcaine/tridactyl#651]
I'm running MacOS High Sierra 10.13.4 (appears to come with Python 2.7.13).

To reproduce:
 
1. Execute :installnative in tridactyl.
2. Run command from clipboard in shell.
3. Script downloads, but then shows the following error:
> Error: Python 3 must exist in PATH.\e[0m
> Please install it and run this script again.\e[0m

**Comment by bovine3dom** [comment]
Have you installed Python 3?

**Comment by pequodification** [comment]
Not yet! I was a little worried it might mess up my OSX install. Is there a key reason it's not compatable with Python 2? Would be handy if it worked out the box.

**Comment by bovine3dom** [comment]
Python 2 will be deprecated soon: https://legacy.python.org/dev/peps/pep-0373/

It's incompatible with Python 3, which is the language our script is written in. We would have to rewrite it quite substantially to support Python 2.

Installing python 3 won't mess up OSX, providing you put it on your path as `python3` rather than `python`, but the installer will do that for you : )

**Comment by bovine3dom** [comment]
I'm closing this as it would be quite a lot of work to make the script work in Python 2.
