### ISSUE TITLE
Issue template / debugging guide

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#662]
Should cover:

- Opening the browser / web console
- Accessing `tri` through the console on the new tab page and about:debugging
- Setting relevant logging levels and attaching those logs
- Including configuration by copying `viewconfig` URI
- Including user.js, prefs.js and userChrome.css

Have I missed anything?

**Comment by glacambre** [comment]
If the issue is about the native messenger, users should probably also tell us if the native messenger exists in ~/.local/share/tridactyl (or the equivalent locations on OSX/Windows) and if the manifest exists in ~/.mozilla/native-messaging-hosts. They should also probably make sure Python3 is installed and available in their $PATH.

**Comment by bovine3dom** [comment]
We should probably include a reminder for people to search for similar issues.

I found a bot that would do that automatically as some point but I have since lost it...
