### ISSUE TITLE
Allow for empty page on `New Tab`

### ISSUE THREAD

**Issue by nikitavoloboev** [cmcaine/tridactyl#678]
I would like to get a blank page on new tab same as [this chrome extension](https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij).

Is this possible to add?

**Comment by antonva** [comment]
Without having tested it, you could try `set newtab file://path/to/blank.html`

**Comment by bovine3dom** [comment]
This used to be "supported" but Mozilla broke it or fixed a security bug depending on your opinion: #379.

File won't work as native must open in a new tab, so you'll get two new tabs.

I suspect easiest thing is to just make a new theme that does `display: none` for the new tab page.

**Comment by glacambre** [comment]
You can use `set newtab about:blank` or use what antonva suggested but Tridactyl's shortctus won't be available.
You could also create an autocommand that inserts a css rule when the new tab page is loaded: `autocmd DocStart moz-extension://.*/static/newtab.html js document.body.style.display = "none"`.
You could also try to find a blank page on the internet and using it as newtab page (here's a black one: http://www.e-try.com/black.htm)

**Comment by ELLIOTTCABLE** [comment]
I'd like to vote for this being a built-in feature, though — while the documentation and help on the unfortunately-necessary builtin newtab page are useful and great, it should be configurable to use a blank, white page instead, once someone knows their way around Tridactyl; y'know?

(In particular, I'd really love a blank, off-white page, with the embossed FireFox logo as it appears on the *default* startpage, with a matching version of the Tridactyl logo embossed right next to it. If I had my 'druthers, anyway. 🤣)

**Comment by glacambre** [comment]
Elliottcable: Your wish is my command. Just save [this file](https://gist.github.com/glacambre/18876c4080fdcbb97114c3f02c8bc9e9) as $profiledir/chrome/userContent.css and restart firefox.

If you want to use your own picture, save it as png, convert it to a string using a base64 converter (which might already be installed on your computer if you're a linux user) and replace the string of characters starting from the coma up to the closing parenthesis with the one from the base64 converter.

**Comment by bovine3dom** [comment]
> I'd like to vote for this being a built-in feature, though

`set newtab about:blank` is already pretty terse. Do you want it better documented? Or is it the styling you want? For that, see #609.

**Comment by ELLIOTTCABLE** [comment]
Wait, I was under the impression that Tridactyl's controls wouldn't work on `about:blank`. I now realize that is not the case! Ignore me completely.

**Comment by ELLIOTTCABLE** [comment]
Okay; now it's not functioning at all — I remember trying this and posting the above; but as of right now, for me, `set newtab about:blank` results in *actual* `about:blank` being opened, not one with Tridactyl's scripts loaded … and is thus unescapable from the keyboard. `/=`

**Comment by glacambre** [comment]
I think the simplest solution is just to use Tridactyl's newtab page with the usercontent.css I suggested (you're free to remove the background image, although I don't see why you would want to :p).

**Comment by bovine3dom** [comment]
I think Mozilla fixed a "bug" where about:blank was more accessible than it ought to have been.

**Comment by ELLIOTTCABLE** [comment]
Again, totally solvable locally — just seems like this should be a first-class feature for all users, nah?

To be clear, I'm suggesting:

1. Ship `static/blank.html` with Tridactyl, which is simply an otherwise-blank page with Tridactyl's page-script included
2. Re-write the consumer of the `'newtab'` setting to special-case the string `"about:blank"`, such that …
3. Opening a new tab will open, instead, `moz-extension://d9f9a28e-e5be-4841-951d-4f9d463d216c/static/blank.html`.

Any reason not to do this? At least until `about:blank` gets ‘unfixed?’

(Again, I personally would love to see a subtle, embossed Tridactyl logo that matches the subtle, embossed FireFox logo on the default start-page … but I dunno if we have any designers on the project. Also, maybe everybody but me wants a *truly* blank start-page. Okay, okay, I'll stop repeating that. 🤣)

**Comment by nikitavoloboev** [comment]
I just ran `:set newtab about:blank` and now new tab opens 'about:blank' and also puts `about:blank` in URL bar. Tridactyl doesn't work either.

How can I reverse this?

**Comment by ELLIOTTCABLE** [comment]
@nikitavoloboev it's currently broken, apparently. That's a bug.

The workaround, right now, is @glacambre's approach above.

Here's, I [forked his examlpe `userContent.css`](https://gist.githubusercontent.com/ELLIOTTCABLE/bc4de14e6b00828f971e8bf617133261/raw/52510108325f71b16e0a6248b7472b31094708ba/userContent.css) and removed the joke content. Save it [in your profile-folder](http://kb.mozillazine.org/index.php?title=UserContent.css).

**Comment by bovine3dom** [comment]
I added a hack on top of another hack and now `set newtab about:blank` kinda works again. See #828 for known issues.

**Comment by nikitavoloboev** [comment]
> approach above

I just read his comment and still confused. What do I need to do?

**Comment by glacambre** [comment]
@nikitavoloboev As @ELLIOTTCABLE said, in order to have a blank newtab page, you need to download [this file](https://gist.githubusercontent.com/ELLIOTTCABLE/bc4de14e6b00828f971e8bf617133261/raw/52510108325f71b16e0a6248b7472b31094708ba/userContent.css) and save it as "userContent.css" in the directory named "chrome" in your firefox profile folder. Also make sure to run `:unset newtab` in order to remove your current newtab setting.

**Comment by nikitavoloboev** [comment]
> Also make sure to run :unset newtab

I can't do that. Because my new tab now opens a page but I am not in normal mode.

**Comment by glacambre** [comment]
The commandline is also available on other websites, so you could go to `https://example.org` and run the command there :).

**Comment by bovine3dom** [comment]
`set newtab about:newtab` should also work a bit less badly in the latest betas (no about:blank in URL bar).
