### ISSUE TITLE
t should be bound to :tabopen by default

### ISSUE THREAD

**Issue by sumnerevans** [cmcaine/tridactyl#68]
Pressing <kbd>T</kbd> (without <kbd>Shift</kbd>) should be bound to `:tabopen` by default.

**Comment by bovine3dom** [comment]
It is bound to that.Do you mean fillcmdline tabopen? The decision not to do that was a conscious one: we don't have completions yet, and this way people can use the firefox omnibar completions. We'll change it once we are happy with the completions, but that's a moderate time away as we need to store history and maybe look at search engine APIs.You can rebind it easily with "bind t fillcmdline tabopen" if you so desire.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 17 November 2017 10:25 pmTo: tridactyl@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [cmcaine/tridactyl] t should be bound to :tabopen by default (#68)  Pressing T (without Shift) should be bound to :tabopen by default.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wschmrdrNS** [comment]
If "t" is going to have to bring in your own newtab page, would it be possible to allow the user to continue to use the command shortcuts, such as "o" for :open ? Having to click the middle of the page a few times because of the default to insert mode gets a bit annoying after a while. Using the :open command after a new tab is livable.

**Comment by wschmrdrNS** [comment]
How about for doing a search engine search in a new tab, such as with duckduckgo?
:tabopen duckduckgo what is the airspeed velocity of an unladen swallow

**Comment by bovine3dom** [comment]
@wschmrdrNS that command already works. I don't understand what you're trying to say.

**Comment by wschmrdrNS** [comment]
No, S is bound to one specific search engine, and not to the specific one mentioned. There are multiple engines that people use to search. whether it's Wikipedia, Dictionary, Youtube, Duckduckgo, etc.

**Comment by madduck** [comment]
Do we really want to hard-code one specific search engine? I vastly prefer ddg, mostly because it gives me access to GOOG with `!g` when I choose, as well as the other search engines, using the [bang codes](https://duckduckgo.com/bang). The one specific search engine in question does the precise opposite and tries hard to lure you into its ecosystem.

**Comment by madduck** [comment]
Also related to #60…

**Comment by Taomach** [comment]
>why would you want o for open when focus is already in the location bar?

I avoid using the firefox addressbar in Vimperator because it behaves differently than vimperator commandline. Differen keybindings, completion logic, completion order, and so on. It also makes you shift the attention from the bottom of the window to its top, and then back, which is irritating, albeit minor.

**Comment by wschmrdrNS** [comment]
I remember the old days of Pentadactyl when you didn't have the address bar at all, and you relied on commands with the bottom bar for that.

**Comment by ahungry** [comment]
You can still get close to that with Waterfox + Vimperator if you do `:set gui=none` (Pentadactyl works well with GNU Icecat v45 as well)

**Comment by bovine3dom** [comment]
@wschmrdrNS @ahungry have you tried the userChrome recommended on the new tab page? It does most of that.

I'll reiterate what I said at the top: we'll change the default bind once we have completions working.

I am also a bit perplexed as to the level of feeling about defaults when you can easily rebind t with `bind t fillcmdline tabopen` and S with `bind S fillcmdline tabopen [your favourite search engine here]` or even `bind S fillcmdline_notrail tabopen https://this.is.custom/q=`.

I understand the "tyranny of defaults", but I think these are the most sensible for most users right now.

**Comment by wschmrdrNS** [comment]
When you talk about finishing completions, I assume that means the suggestions when you start typing with :open or :tabopen ?

Also, as you've been pushing the bind option... is there some sort of rc file where this is saved?

Having "S" and "s" tied to the evil alphabet corporation is understandable since that was the previous behavior in Pentadactyl; hopefully there's some sort of documentation that will explain customizing this so you don't have to go over it 371,292 times.

**Comment by bovine3dom** [comment]
@wschmrdrNS `bind`s are currently stored in the Firefox `sync` storage. An `rc` file is blocked by the lack of a native messenger. Re. completions: yes.

PRs improving documentation would be very welcome! One would just need to edit the docstrings in excmds.ts.

The latest beta on the AMO has a much improved help file (there's even a link to the default bindings...).

We have been a bit maverick about writing things without documenting them, and I apologise for that : )

**Comment by wschmrdrNS** [comment]
If I had a nickel for every time I've written something without documenting, I could pay you a salary to get this to a stable state. ;) Not sure if I'll have time to submit a PR with all these other projects going on.
