### ISSUE TITLE
Buffer and bufferall should highlight items based on the container they are in

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#720]
I don't know what would look best. Maybe an underline or border bottom? Probably a muted version of the colour via HSL?

**Comment by antonva** [comment]
A coloured icon next to the url wouldn't take up too much space and narrows down which container you might be talking about.

**Comment by caputchinefrobles** [comment]
I dunno if its related but on greenmat we have background color (used as gradient) on a td used in completions table through the .prefix class. Perhaps it could be used to highlight container colors:
![image](https://user-images.githubusercontent.com/8964036/41689527-650d7100-74c7-11e8-969f-db2ad85c0366.png)

**Comment by glacambre** [comment]
I did several attempts, here they are:
1) ![screenshot_2018-06-21-19 24 46](https://user-images.githubusercontent.com/11534587/41736968-411ce47a-758e-11e8-850b-fd88961c7d48.png)
2) ![screenshot_2018-06-21-19 26 49](https://user-images.githubusercontent.com/11534587/41736971-41539c7c-758e-11e8-84ef-ae57441a4fbb.png)
3) ![screenshot_2018-06-21-19 27 40](https://user-images.githubusercontent.com/11534587/41736972-417d8b2c-758e-11e8-8105-8fa11b7e2ba6.png)
4) ![screenshot_2018-06-21-19 28 54](https://user-images.githubusercontent.com/11534587/41736974-41ae8fce-758e-11e8-98a2-f998d64ee407.png)
5) ![screenshot_2018-06-21-19 29 50](https://user-images.githubusercontent.com/11534587/41736976-41df5f5a-758e-11e8-9fc1-6ef46818042e.png)
6) ![screenshot_2018-06-21-19 53 32](https://user-images.githubusercontent.com/11534587/41736977-4224e818-758e-11e8-8c39-ae41c14d7d09.png)

I think I prefer 3 or 6. 6 might be slightly complicated to implement because icons are stored as black and white SVG files and we'll need to apply the colour ourselves (I have no idea how to do this, I just took screenshots of the icons).

**Comment by bovine3dom** [comment]
Re SVG colour, did you try https://css-tricks.com/almanac/properties/f/fill/ ?

What happens if it's one of the # or % tabs?

I don't hate 5 but think 6 is best. 1 is fantastically bad.

**Comment by glacambre** [comment]
>What happens if it's one of the # or % tabs?

The symbols were overwritten.

> did you try https://css-tricks.com/almanac/properties/f/fill/ ?

Yep. I took a look at what happened in about:preferences and it appears I also needed to use the `-moz-context-properties: fill;` css attribute.

Here's how it looks when you don't replace the `#`/`%` symbols:

![screenshot_2018-06-22-06 36 41](https://user-images.githubusercontent.com/11534587/41758360-693e7270-75e8-11e8-8660-c5646f3e2898.png)

With slightly smaller icons:
![screenshot_2018-06-22-06 38 08](https://user-images.githubusercontent.com/11534587/41758361-696a9530-75e8-11e8-8304-80e96a9b3876.png)

With less padding for the symbol column:
![screenshot_2018-06-22-06 39 23](https://user-images.githubusercontent.com/11534587/41758362-6990e15e-75e8-11e8-899c-73dded8bf2b0.png)

I think the last one is quite good for a default theme.

**Comment by bovine3dom** [comment]
Yeah, the last one is nice, but what's happening with your first tab? Why does it have two empty boxes?

**Comment by glacambre** [comment]
The empty boxes are caused by urls being replaced with `zXssPrevented` just like in https://github.com/cmcaine/tridactyl/issues/701 . I believe you can't use resources from privileged tabs in the command line.
Don't you have the same issue when using `:buffer` while an `about:debugging` tab is open?

**Comment by bovine3dom** [comment]
Yeah, but I only get one of them. Does that mean we're not allowed to know the container of an about:* tab?
