### ISSUE TITLE
Make hints mode letters again

### ISSUE THREAD

**Issue by jeremybrhere** [cmcaine/tridactyl#779]
I recieved an update and now have numbers to follow links in hints mode. I do not want numbers as I have to move 2 rows to reach them. How do I disable this numbers "feature"?

**Comment by glacambre** [comment]
There are two possibilities, you either set `hintnames` to `numeric` or set `hintchars` to `012345689`. Make sure that `hintnames` is set to `short` and `hintchars` to something like `hjklmgfdsqyuioptrezancxwb`. Also make sure that `hintfiltermode` is set to `simple`.

`:h hint` will take you to the documentation for hint mode where you can read more about what these settings do.

It's weird that the update changed these settings for you. Are you sure you didn't change them yourself? Did you copy someone else's tridactylrc?

**Comment by bovine3dom** [comment]
I do like the idea of changing the hintchars every now and then to annoy our users.

Maybe next month we should use emoji? :smiling_imp:

**Comment by glacambre** [comment]
The tridactylrc themselves aren't synced but I think extension settings are indeed synchronized, the problem indeed probably comes from that :)

**Comment by jeremybrhere** [comment]
Thanks guys! So if I keep a discrete ~/.tridactylrc on each box can I avoid the leaking config that tridactyl is not likely responsible for?

**Comment by glacambre** [comment]
`:set storageloc local` might do the trick, although I'm not 100% certain it'll work.

**Comment by jeremybrhere** [comment]
Cool, and thanks for this project. I just about my mind when Quantum broke VimFX.

**Comment by bovine3dom** [comment]
> Thanks guys! So if I keep a discrete ~/.tridactylrc on each box can I avoid the leaking config that tridactyl is not likely responsible for?

Yeah, there are a few things you could do:

- `set storageloc local` (although there were some reports of this being broken - I don't think many people use it) will stop Tridactyl from using the sync storage; or
- Have `sanitise ...` uncommented if you're using my .tridactylrc (but there's a bug that means that doesn't work sometimes, fixed in the betas) although that itself will be leaky and wipe the settings on anything else signed into sync; or
- Use the betas as I don't think they work with Firefox sync; or
- Use the beta on one machine and stable on another; or
- Don't sign into Firefox Sync on some machines.

Through sheer incompetence, I employ a mixture of the last three strategies :)

I'm glad the project has given you solace, but you may find that Vimium-FF is more like VimFX than we are. We're aiming to be more like Vimperator (but with a different set of bugs).
