### ISSUE TITLE
yanking hints does not respect yankto config

### ISSUE THREAD

**Issue by peff** [cmcaine/tridactyl#831]
@glacambre Thanks for working on the x-selection branch (I couldn't find an open PR to comment on). I wanted a similar thing and had a hacky implementation (peff/tridactyl@44f4bbd096c6f654bd5590b156da9c3fd884a655) which mostly just ran `xsel -b -o | xsel -p -i` to simulate your "both" mode.

One thing mine did that yours does not (yet) do is respect `yankto` when yanking hints. It should be easy to add, but there's one thing I'm not clear on: where should helper functions go to be accessible to both the hinting code and `excmds.ts`? The hinting code can't just import from `excmds` because those helpers are marked as background. But I'm really unclear on what that means precisely. Any pointers?

**Comment by glacambre** [comment]
>But I'm really unclear on what that means precisely.

This is the most confusing part of Tridactyl IMO. Webextensions have two kind of processes, one that runs in the background and one that runs in every tab. These kinds of processes do not have the same permissions so we can't just run everything in a single process.

In order to have every excmd available both to the content and background script, we have a [python script](https://github.com/cmcaine/tridactyl/blob/master/scripts/excmds_macros.py) that processes `excmds.ts` and creates `excmds_background.generated.ts` and `excmds_content.generated.ts`. The background file will contain all the excmds marked with `//background`. It will also contain functions named after the ones marked with `//content`,  but these functions will use `messageTab()` in order to call excmds in the content script.

The simplest way to work around these architectural restrictions is probably to use a messaging function (probably `messageActiveTab("commandline_background",  "setclip", [string_to_copy])`) to call whatever function you need.

Hopefully most of the pain of working with messaging will go away with [v2](https://github.com/cmcaine/tridactyl/issues/434) but I'm afraid it won't, the webextension ecosystem is built around messaging.

**Comment by bovine3dom** [comment]
> every excmd available both to the content and background script

That's not quite right - all excmds are available from background. Content only has those that work in content.

If you're in the background you should just be able to import .excmds_background.generated.ts. Otherwise, my favourite way is to just use our excmd parser with e.g. `Messaging.message("commandline_background", "recvExStr", ["yank " + url])`.

Some day we'll get around to doing it more sensibly...

**Comment by bovine3dom** [comment]
@peff I've accidentally fixed this as part of preparing for #434. I'll merge it soon:tm:.

**Comment by bovine3dom** [comment]
Fixed in https://github.com/cmcaine/tridactyl/commit/e99b30f.

**Comment by peff** [comment]
Thanks, I tested and this works perfectly. Procrastination wins again!
