### ISSUE TITLE
Command line is being displayed incorrectly with a left-side Firefox scrollbar

### ISSUE THREAD

**Issue by aleks-m** [cmcaine/tridactyl#909]
Hi. 

I am using a left-side scrollbar in Firefox and looks like Tridactyl command line works incorrectly with it.

*   Steps to reproduce:

    1.  Set `layout.scrollbar.side` to 3 in `about:config`
    2.  Open tridactyl command line
    3.  Command line is being displayed behind the scrollbar:

![2018-08-14-150126_579x857_scrot](https://user-images.githubusercontent.com/28104246/44091165-3c817f86-9fd5-11e8-93ca-7699e134af7f.png)

*   Tridactyl version:
1.13.1-1.13.1
*   Firefox version :
61.0.1 (64-bit)
*   URL of the website the bug happens on:
any
*   Config :
https://gist.github.com/aleks-m/270ede00d1fc7efe7e3e48516cf5adb1
*  userChrome:
I have a custom userChrome.css - https://gist.github.com/aleks-m/93221232d85c9f18e8ffdc8c42789fed 
but this issue is reproducible even on a default config, without any userChrome.css at all.

**Comment by glacambre** [comment]
Hi, thank you for reporting this issue. It looks like this issue can be fixed by removing this rule:
https://github.com/cmcaine/tridactyl/blob/312dfedabe4d9c9913d689feba960a3a4f200c78/src/static/css/content.css#L4

@cmcaine: You seem to be the one who [added](https://github.com/cmcaine/tridactyl/commit/20edc42b3ec96ae68dee022e929254ccf77a4e03#diff-756c4f79db3fc64f85dc50642e4377baR4) it, was this rule necessary to fix a bug?

**Comment by bovine3dom** [comment]
Seems to be fine without it.
