### ISSUE TITLE
ex command completion improvements

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#912]
- [x] display aliases
- [x] think about whether we want function signature - not sure it's that useful and I think it will mostly just serve to terrify new users (hence the block on the next release)

Thanks, btw, @glacambre - it's really neat : )

**Comment by glacambre** [comment]
I think having types is useful but we should probably display them in a shell-like fashion. Instead of having `back    (n?: number) => void    Navigate back one page in history.` we should display something like `back   [number]    Navigate $number pages back (defaults to 1)`. Open would become `open   [string [string...]]   Open a new page in the current tab.`.

Also I just noticed that currently typing `b` expands to `buffer` in the completion mechanism and thus prevents every other completion starting with `b` from being displayed until the user types another letter that is not `u`. This expansion should probably only happen when the command line contains a space.

**Comment by bovine3dom** [comment]
I'd noticed the same happening with `t` for `tabopen` but forgot to document it...

**Comment by antonva** [comment]
Pressing enter on a highlighted completion source should not execute it but put it on the command line.

**Comment by bovine3dom** [comment]
That sounds awful.

Vimperator solved it by having highlighted completions appearing in the command line.

They also had it so that whatever was at the top would get chosen if eg you were filtering buffers.

It would require quite a big rewrite.

I don't like the idea of having to press enter twice (my main issue being `buffer` for changing tabs).

**Comment by bovine3dom** [comment]
Oh, do you just mean ex command completions? I'm not sold - that's what we have space for.

**Comment by antonva** [comment]
I just meant for excmds yeah but space is okay I guess. Not what I'm used to.

**Comment by bovine3dom** [comment]
We just need #304 and then everyone can have the binds they want, rather than just me : )

**Comment by bovine3dom** [comment]
I have already learnt to ignore the function signatures but I'm still not convinced about them.

I think displaying more help would be a better use of the space.

**Comment by glacambre** [comment]
I'm currently working on getting better type info in `.metadata.generated.ts`, which would probably help generating shell-like types. We'll then be able to evaluate whether they're useful or not (and if they're not that's ok, having type metadata will still be useful when we'll try to get rid of the macro preprocessor).

**Comment by bovine3dom** [comment]
Sounds good, but I don't really see the need for types on the completions given that they can only be numbers or strings, which I think is usually clear from context.

I'll probably agree with you more once #789 lets us get more information about flags rather than just having `...args`.
