### ISSUE TITLE
Provide for key press aliases

### ISSUE THREAD

**Issue by madduck** [cmcaine/tridactyl#916]
An extension of mine uses `<C-y>`, but I am used to `<C-S-l>` for that functionality. It would be awesome if Tridactyl would let me say something like

```
keyalias <C-S-l> <C-y>
```

meaning that when I press `C-S-l`, it actually invokes `<C-y>`.

Ideally, it would happen in such a way that I could still `bind` `C-y` to something else, or use the Tridactyl default mapping. I.e. Pressing `C-S-l` should invoke `<C-y>` outside of Tridactyl.

**Comment by glacambre** [comment]
I already tried to simulate keypresses for other stuff and couldn't get it to work. If you just need inter-extension communication there's [a way](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage) to do this, but it requires coordination between both Tridactyl and the other extension.

**Comment by bovine3dom** [comment]
We can't fake key events so I don't think there's any way we can do this and have it affect other extensions and pages. We could make it work for Tridactyl.

**Comment by madduck** [comment]
Okay, so if I got the other extension to do the right thing when it received a message sent by `runtime.sendMessage`, then all we'd have to do would be to create an `extcmd` in Tridactyl that I could bind to a key?

**Comment by glacambre** [comment]
Yup, in fact there's very little worked required on Tridactyl's side, you could do it yourself with something like this:
`alias passff_menu jsb browser.runtime.sendMessage("passff@invicem.pro", {whatever_passff_requires: here}}`
`bind <C-S-l> passff_menu`.

Related issue: https://github.com/cmcaine/tridactyl/issues/646

**Comment by madduck** [comment]
OMG, that's awesome, except of course Firefox won't allow me to bring up a UI element in response to a message like this, for security reasons. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup

Anyway, I guess this issue can be closed as WOULD-BE-NICE-BUT-CANTFIX

**Comment by glacambre** [comment]
I see two solutions: either have passff reimplement their popup menu in HTML so that they can open in whenever they want or reimplement passff in Tridactyl. Both these solutions require far more work than what would be needed if these arbitrary restrictions didn't exist.

If you want to reimplement passff in Tridactyl you could do something like this:
```
alias get_password composite get_current_url | jsb -p tri.native.run("pass -c " + JS_ARG).then(cmd => tri.excmds.fillinput(cmd.content))
bind --mode=insert <C-S-l> get_password
```
What this does is create an alias named get_password. This alias will grab the url of the current page and pipe it to an arbitrary js command in the background (webextensions have multiple processes, one that lives in the background that can't access pages and others that live in pages and can't run software on your computer).
The background process will run `pass -c $URL_OF_THE_CURRENT_WEBSITE` on your computer, which I believe will output the password for the current website. This output will then be sent back to the page's process to be inserted in the last selected input.

This is terrible, probably buggy and I'm sure will require a few adjustments. But it's possible.
